main: me.manny.unity.Unity
name: Manny
version: 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.00.0.0.0.0.0.0.0.0.0.0.0.0.0.00.0.0.0.0.0.0.0.0.69
description: Created by ItsManny Unity BungeeCord Network.
author: ItsManny